# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/go:1.18.6
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo "Hello, World!"
            echo "Mujahid Testing here"
      - run:
          name: Prep env
          command: |
            sudo apt update
            sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
            mkdir -p /home/circleci/go/src
            go install
            pushd plugins/packages/compat/tokens
            go generate
            popd
      - run:
          name: "Check for lates Upstream"
          command: |
            curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Muubash/heimdall/merge-upstream -d '{"branch":"develop"}'
      - run:
          name: "Clone the Heimdall Repo and build"
          command: |
            git clone https://oauth2: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@github.com/Muubash/heimdall.git
            cd ./heimdall && make build
            cd ./heimdall/build && ls
            


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
